# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Carolyn Stienen
title: Machine Learning Engineer
email: carrie.stienen@gmail.com
website: carriestienen.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: carriestienen
github_username:  carriestienen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: carriestienen
linkedin_username: carrie-stienen-53533449
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: TikTok
  icon: fas fa-music
  url: https://www.tiktok.com/@codingwithcarrie
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
- title: Twitch
  icon: fab fa-twitch
  url: https://www.twitch.tv/carrie_greenbow
- title: Duolingo
  icon: fas fa-language
  url: https://www.duolingo.com/profile/Cstienen
- title: Medium
  icon: fab fa-medium
  url: https://carriestienen.medium.com/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Carrie and I'm a machine learning engineer. As well as machine learning, I have experience in NLP, data analsyis, and data visualization. I have a master's degree in Data Science from DePaul University and have worked at a number of companies.

  I am most skilled in: <mark>Python</mark>, <mark>NLTK</mark>, <mark>R</mark>, <mark>Mathematics</mark> and <mark>Statistics</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GoBot
        link: https://github.com/carriestienen/GoBot
        # link_text: Project Website
        additional_links:
          - title:  carriestienen/GoBot
            icon: fab fa-github
            url: https://github.com/carriestienen/GoBot
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An app that evaluates Japanese language text and determines its politeness level: casual, polite, honorific, or humble.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning NLP principles. It taught me how to perform word vectorization in different languages and recognize symantic patterns.
        application: |
          When to use humble, honorific, or polite language can be a challenge for new Japanese learners who speak English as a first language. It's often difficult to differentiate between them. This code can help make those distinctions and, with context clues, reveal when it's appropriate to use what type of language.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TrustYou
        link: https://www.trustyou.com/
        # link_text: boringcompany.com
        sub_title: Japanese NLP Analyst
        caption: August 2021 - December 2021
        quote: >
          TrustYou is a hotel reputation management software platform. 
        description: | # this will include new lines to allow paragraphs
            Developed language processing code that analyses sentiment. This code was used to aggregate guest feedback into a software dashboard so that hotel management could comprehend guest satisfaction instantly. Evaluated customer reviews in Japanese in order to expand review corpora and make sure our NLP model was properly fit to the dataset. Developed Context-Free Grammars for an NLP pipeline using python and NLTK.

      - layout: left
        title: American Medical Association
        link: https://www.ama-assn.org/
        # link_text: boringcompany.com
        sub_title: Data Science Intern
        caption: February 2020 - March 2021
        quote: >
          AMA is the largest association of physicians and medical students in the United States
        description: | # this will include new lines to allow paragraphs
            Developed data visualizations in Tableau and PowerBI for sales and marketing teams to view results of past campaigns. Implemented web scraping and data triangulation using Python. Data modification using Pandas, Numpy. Data modeling in ScikitLearn. Wrote data analysis reports in Jupyter Notebook. Database management in SQL.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DePaul University
        caption: 2019 - 2021
        sub_title: M.S. Data Science
        quote: >
          Established in 1898, DePaul University, the largest Catholic university in the United States, offers academically excellent, flexible, practical programs of study in a student-focused learning environment. DePaul is the 13th-largest private, not-for-profit university in the nation.
        description: | # this will include new lines to allow paragraphs
          I attended DePaul University at first in person and then moved online after the start of the COVID-19 pandemic. I took several classes, including classes in data science, analysis, machine learning, data visualization, and data mining.
        coursework: |
          Courses include machine learning, data visualization, data mining, big data, and neural networks.

      - layout: left
        title: University of Wisconsin-Madison
        caption: 2008 - 2013
        sub_title: B.S. Mathematics & Computer Science, certificate in Technical Japanese
        quote: >
          Since its founding in 1848, the UW-Madison campus has been a catalyst for the extraordinary. As a public land-grant university and prolific research institution, its students, staff, and faculty members partake in a world-class education and solve real-world problems.
        description: | # this will include new lines to allow paragraphs
          I received my Bachelor's degree from UW-Madison in 2013. I double majored in Mathematics and Computer Science, and took part in the International Internship Program where I worked abroad in Nara, Japan for a semester.
        coursework: |
          Courses include algorithms, number theory, combinatorics, compilers, and operating systems.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in machine learning and data science some of my other interests and hobbies are:
      - Crossword Puzzles
      - Dogs
      - Learning new languages

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
